# Generated by Django 5.0.6 on 2024-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='names',
            new_name='name',
        ),
    ]
