# Generated by Django 5.0.6 on 2024-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_saleitem_delete_saleitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='card_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='mpesa_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
