# Generated by Django 5.0.6 on 2024-05-16 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_saleitem_payment_method_saleitem_card_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='staff',
        ),
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcecredits',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.network'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecredits',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADM', 'Admin'), ('STF', 'Staff'), ('MNG', 'Manager')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
