# Generated by Django 5.0.6 on 2024-05-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_remove_appointments_staff_remove_saleitem_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
