# Generated by Django 5.0.6 on 2024-05-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_remove_saleitem_customer_saleitem_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='customer_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
