# Generated by Django 5.0.6 on 2024-05-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_saleitem_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
