# Generated by Django 5.0.6 on 2024-05-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_alter_saleitem_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.products'),
        ),
    ]
