# Generated by Django 5.0.6 on 2024-05-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_saleitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
