# Generated by Django 5.0.6 on 2024-05-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_rename_name_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='customer_mobile',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.customer'),
        ),
    ]
