# Generated by Django 5.0.6 on 2024-05-18 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_remove_saleitem_customer_mobile_saleitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='card_payment',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='mpesa_payment',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='user',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mpesa_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.sale'),
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
