# Generated by Django 5.0.6 on 2024-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_remove_saleitem_card_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
