# Generated by Django 5.0.6 on 2024-05-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_location_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
    ]
